# Generated by Django 6.0.3 on 2026-03-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_drink_stock_qty_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='sugar',
            field=models.CharField(help_text='Sweetness levels offered for this drink, as percentages. Enter comma-separated values, e.g. 10%, 20%, 30%, 50%, 70%, 100%.', max_length=128, verbose_name='Sugar (% options)'),
        ),
    ]
