# Generated by Django 6.0.3 on 2026-03-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_drink_sugar_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a product photo (JPG, PNG, WebP, etc.).', upload_to='drinks/'),
        ),
    ]
