# Generated by Django 6.0.3 on 2026-03-25 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_drink_image_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive staff are hidden from clock-in and lists by default.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cafe_staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(help_text='When the staff member started work.')),
                ('clock_out', models.DateTimeField(blank=True, help_text='When the staff member finished work (empty = still on shift).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='polls.staff')),
            ],
            options={
                'db_table': 'cafe_staff_time_log',
                'ordering': ['-clock_in'],
            },
        ),
    ]
